development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: mgmt_development
  pool: 5
  username: mgmt
  password: mgmt

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: mgmt_test
  pool: 5
  username: mgmt
  password: mgmt

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: mgmt_production
  pool: 5
  username: mgmt
  password: mgmt